repos:
  - repo: local
    hooks:
      - id: check-version
        name: Check Cargo.toml Version Matches Git Tag
        entry: ./ci/check_version.sh
        language: script
        types: [toml]
        pass_filenames: false

      # - id: rustfmt
      #   name: rustfmt
      #   description: Check if all files follow the rustfmt style
      #   entry: cargo fmt --all -- --color always
      #   language: system
      #   pass_filenames: false
