[package]
name = "jposit"
version = "0.2.1"
edition = "2021"

# [workspace]

[lib]
name = "jposit"
crate-type = ["cdylib"]

[dependencies]
colored = "3"
posit = { path = "../" }

[build-dependencies]
