[package]
name = "jposit"
version = "0.3.0-dev"
edition = "2021"

# [workspace]

[lib]
name = "jposit"
crate-type = ["cdylib"]

[dependencies]
colored = "3"
pyo3 = { version = "0.18", features = ["extension-module"] }
posit = { path = "../" }

[build-dependencies]
cbindgen = "0.29.0"
