name: CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: macos-latest
            target: arm64
        python-version: [3.9, 3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Prepare environment
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install maturin pip
      - name: Run maturin and demo
        run: |
          source .venv/bin/activate
          cd py-posit
          maturin develop
          make demo

      - name: Publish wheel
        if: ${{ success() }}
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          source .venv/bin/activate
          cd py-posit
          maturin publish --no-sdist --skip-existing -o wheels -i python --username __token__
